language: cpp
os: windows

before_install:
  - choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional --passive --locale en-US"

script:
  - msbuild /p:Configuration=Release RefactaMasta.sln
