language: cpp
os: windows

before_install:
  - choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional --passive --locale en-US"

script:
  - "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\msbuild.exe /p:Configuration=Debug RefactaMasta.sln"